version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: social_postgres
    environment:
      POSTGRES_DB: social_media
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - social_network

  redis:
    image: redis:7-alpine
    container_name: social_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - social_network

  app:
    build:
      context: .
      dockerfile: deployments/docker/Dockerfile
    container_name: social_app
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=password123
      - DB_NAME=social_media
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=your-super-secret-jwt-key
    depends_on:
      - postgres
      - redis
    networks:
      - social_network

volumes:
  postgres_data:
  redis_data:

networks:
  social_network:
    driver: bridge